development: &DEV
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: letsrails_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  <<: *DEV
  database: letsrails_test

production:
  <<: *DEV
